In [1]:
import pandas as pd

In [22]:
app_train = pd.read_csv("C:/SHARYU/NEU/Unsupervised2/Project/app_train_removed_all_78.csv")
app_train.drop(app_train.columns[0],axis=1,inplace=True)
app_train

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,NAME_TYPE_SUITE,...,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_18,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,Family,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,Revolving loans,M,Y,Y,0,67500.000,135000.0,6750.0,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,Cash loans,F,N,Y,0,135000.000,312682.5,29686.5,Unaccompanied,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,Cash loans,M,N,Y,0,121500.000,513000.0,21865.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,100008,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,"Spouse, partner",...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
6,100009,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,Unaccompanied,...,1,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,100011,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,Children,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
9,100012,Revolving loans,M,N,Y,0,135000.000,405000.0,20250.0,Unaccompanied,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
10,100014,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
11,100015,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,Children,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
12,100016,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
13,100017,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
14,100018,Cash loans,F,N,Y,0,189000.000,773680.5,32778.0,Unaccompanied,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
15,100019,Cash loans,M,Y,Y,0,157500.000,299772.0,20160.0,Family,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
16,100020,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
17,100021,Revolving loans,F,N,Y,1,81000.000,270000.0,13500.0,Unaccompanied,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18,100022,Revolving loans,F,N,Y,0,112500.000,157500.0,7875.0,Other_A,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
19,100023,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
20,100024,Revolving loans,M,Y,Y,0,135000.000,427500.0,21375.0,Unaccompanied,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
21,100025,Cash loans,F,Y,Y,1,202500.000,1132573.5,37561.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
22,100026,Cash loans,F,N,N,1,450000.000,497520.0,32521.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
23,100027,Cash loans,F,N,Y,0,83250.000,239850.0,23850.0,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
24,100029,Cash loans,M,Y,N,2,135000.000,247500.0,12703.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
25,100030,Cash loans,F,N,Y,0,90000.000,225000.0,11074.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
26,100031,Cash loans,F,N,Y,0,112500.000,979992.0,27076.5,Unaccompanied,...,0,0,1,0,0.0,0.0,0.0,0.0,2.0,2.0
27,100032,Cash loans,M,N,Y,1,112500.000,327024.0,23827.5,Family,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,100033,Cash loans,M,Y,Y,0,270000.000,790830.0,57676.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
29,100034,Revolving loans,M,N,Y,0,90000.000,180000.0,9000.0,Unaccompanied,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307481,456225,Cash loans,M,N,Y,0,225000.000,297000.0,19975.5,Family,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307482,456226,Cash loans,F,Y,Y,0,225000.000,500566.5,34969.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307483,456227,Cash loans,F,N,Y,0,99000.000,247275.0,16479.0,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
307484,456228,Cash loans,F,Y,N,0,540000.000,545040.0,35617.5,Unaccompanied,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307485,456229,Revolving loans,F,N,Y,1,270000.000,180000.0,9000.0,Family,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307486,456230,Cash loans,F,Y,Y,1,292500.000,355536.0,18283.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
307487,456231,Cash loans,M,N,Y,0,117000.000,1071909.0,31473.0,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,8.0
307488,456232,Cash loans,F,N,N,0,157500.000,135000.0,13351.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,1.0
307489,456233,Cash loans,F,N,Y,0,225000.000,521280.0,23089.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
307490,456234,Cash loans,M,N,Y,0,81000.000,135000.0,9148.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307491,456235,Cash loans,M,Y,Y,2,90000.000,1078200.0,31522.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307492,456236,Cash loans,M,Y,Y,0,585000.000,1575000.0,43443.0,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307493,456237,Cash loans,F,N,Y,0,135000.000,946764.0,37678.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307494,456238,Cash loans,M,Y,N,1,270000.000,479700.0,46858.5,Family,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,1.0
307495,456239,Cash loans,M,Y,N,0,180000.000,808650.0,23773.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307496,456240,Revolving loans,F,N,N,0,360000.000,337500.0,16875.0,Family,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307497,456241,Cash loans,F,Y,Y,0,180000.000,270126.0,12028.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
307498,456242,Cash loans,M,Y,Y,0,198000.000,1312110.0,52168.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307499,456243,Cash loans,F,N,Y,0,81000.000,225000.0,12694.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0
307500,456244,Cash loans,F,N,Y,0,261000.000,1303812.0,35982.0,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0
307501,456245,Cash loans,F,N,Y,3,81000.000,269550.0,11871.0,Unaccompanied,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307502,456246,Cash loans,F,N,Y,1,94500.000,225000.0,10620.0,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307503,456247,Cash loans,F,N,Y,0,112500.000,345510.0,17770.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
307504,456248,Cash loans,F,N,Y,0,153000.000,331920.0,16096.5,Unaccompanied,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307505,456249,Cash loans,F,N,Y,0,112500.000,225000.0,22050.0,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
307506,456251,Cash loans,M,N,N,0,157500.000,254700.0,27558.0,Unaccompanied,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,Cash loans,F,N,Y,0,72000.000,269550.0,12001.5,Unaccompanied,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,Cash loans,F,N,Y,0,153000.000,677664.0,29979.0,Unaccompanied,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,Cash loans,F,N,Y,0,171000.000,370107.0,20205.0,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,Cash loans,F,N,N,0,157500.000,675000.0,49117.5,Unaccompanied,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [53]:
app_train.CODE_GENDER.unique()

array(['M', 'F', 'XNA'], dtype=object)

In [54]:
#Label Encoder

# Create a label encoder object
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le_count = 0

# Iterate through the columns
for col in app_train:
    if app_train[col].dtype == 'object':
        # If 2 or fewer unique categories
        if len(list(app_train[col].unique())) <= 2:
            # Train on the training data
            le.fit(app_train[col])
            # Transform both training and testing data
            app_train[col] = le.transform(app_train[col])
            #app_test[col] = le.transform(app_test[col])
            
            # Keep track of how many columns were label encoded
            le_count += 1
            
print('%d columns were label encoded.' % le_count)

0 columns were label encoded.

In [55]:
# One-Hot encoding of categorical variables

app_train = pd.get_dummies(app_train)
#app_test = pd.get_dummies(app_test)

print('Training Features shape: ', app_train.shape)
#print('Testing Features shape: ', app_test.shape)

Training Features shape:  (307511, 196)

In [56]:
app_train

,SK_ID_CURR,NAME_CONTRACT_TYPE,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,REGION_POPULATION_RELATIVE,DAYS_BIRTH,...,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes
0,100002,0,0,1,0,202500.000,406597.5,24700.5,0.018801,-9461,...,0,0,0,0,0,0,1,0,1,0
1,100003,0,0,0,0,270000.000,1293502.5,35698.5,0.003541,-16765,...,0,1,0,0,0,0,0,0,1,0
2,100004,1,1,1,0,67500.000,135000.0,6750.0,0.010032,-19046,...,0,0,0,0,0,0,0,0,0,0
3,100006,0,0,1,0,135000.000,312682.5,29686.5,0.008019,-19005,...,0,0,0,0,0,0,0,0,0,0
4,100007,0,0,1,0,121500.000,513000.0,21865.5,0.028663,-19932,...,0,0,0,0,0,0,0,0,0,0
5,100008,0,0,1,0,99000.000,490495.5,27517.5,0.035792,-16941,...,0,0,0,0,0,0,0,0,0,0
6,100009,0,1,1,1,171000.000,1560726.0,41301.0,0.035792,-13778,...,0,0,0,0,0,0,0,0,0,0
7,100010,0,1,1,0,360000.000,1530000.0,42075.0,0.003122,-18850,...,0,0,0,0,0,0,0,0,0,0
8,100011,0,0,1,0,112500.000,1019610.0,33826.5,0.018634,-20099,...,0,0,0,0,0,0,0,0,0,0
9,100012,1,0,1,0,135000.000,405000.0,20250.0,0.019689,-14469,...,0,0,0,0,0,0,0,0,0,0
10,100014,0,0,1,1,112500.000,652500.0,21177.0,0.022800,-10197,...,0,0,0,0,0,0,0,0,0,0
11,100015,0,0,1,0,38419.155,148365.0,10678.5,0.015221,-20417,...,0,0,0,0,0,0,0,0,0,0
12,100016,0,0,1,0,67500.000,80865.0,5881.5,0.031329,-13439,...,0,0,0,0,0,0,0,0,1,0
13,100017,0,1,0,1,225000.000,918468.0,28966.5,0.016612,-14086,...,0,0,0,0,0,1,0,0,1,0
14,100018,0,0,1,0,189000.000,773680.5,32778.0,0.010006,-14583,...,0,0,0,0,0,1,0,0,1,0
15,100019,0,1,1,0,157500.000,299772.0,20160.0,0.020713,-8728,...,0,0,0,0,0,0,0,0,0,0
16,100020,0,0,0,0,108000.000,509602.5,26149.5,0.018634,-12931,...,0,0,0,0,0,0,0,0,0,0
17,100021,1,0,1,1,81000.000,270000.0,13500.0,0.010966,-9776,...,0,0,0,0,0,0,0,0,0,0
18,100022,1,0,1,0,112500.000,157500.0,7875.0,0.046220,-17718,...,0,0,0,0,0,0,1,0,1,0
19,100023,0,0,1,1,90000.000,544491.0,17563.5,0.015221,-11348,...,0,0,0,0,0,0,0,0,0,0
20,100024,1,1,1,0,135000.000,427500.0,21375.0,0.015221,-18252,...,0,0,0,0,0,0,1,0,1,0
21,100025,0,1,1,1,202500.000,1132573.5,37561.5,0.025164,-14815,...,0,0,0,0,0,0,0,0,0,0
22,100026,0,0,0,1,450000.000,497520.0,32521.5,0.020713,-11146,...,0,0,0,0,0,1,0,0,1,0
23,100027,0,0,1,0,83250.000,239850.0,23850.0,0.006296,-24827,...,0,0,1,0,0,0,0,0,1,0
24,100029,0,1,0,2,135000.000,247500.0,12703.5,0.026392,-11286,...,0,0,0,0,0,1,0,0,1,0
25,100030,0,0,1,0,90000.000,225000.0,11074.5,0.028663,-19334,...,0,0,0,0,0,0,1,0,1,0
26,100031,0,0,1,0,112500.000,979992.0,27076.5,0.018029,-18724,...,0,0,0,0,0,0,0,1,0,1
27,100032,0,0,1,1,112500.000,327024.0,23827.5,0.019101,-15948,...,0,0,0,0,0,0,0,0,0,0
28,100033,0,1,1,0,270000.000,790830.0,57676.5,0.046220,-9994,...,0,0,0,0,0,0,0,0,0,0
29,100034,1,0,1,0,90000.000,180000.0,9000.0,0.030755,-10341,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307481,456225,0,0,1,0,225000.000,297000.0,19975.5,0.008575,-20644,...,0,0,0,0,0,0,0,0,0,0
307482,456226,0,1,1,0,225000.000,500566.5,34969.5,0.031329,-14106,...,0,1,0,0,0,0,0,0,1,0
307483,456227,0,0,1,0,99000.000,247275.0,16479.0,0.007330,-24911,...,0,0,0,0,0,0,1,0,1,0
307484,456228,0,1,0,0,540000.000,545040.0,35617.5,0.032561,-12847,...,0,0,0,0,0,0,0,0,0,0
307485,456229,1,0,1,1,270000.000,180000.0,9000.0,0.003813,-11973,...,0,0,0,0,0,0,0,0,0,0
307486,456230,0,1,1,1,292500.000,355536.0,18283.5,0.072508,-16010,...,0,0,0,0,0,1,0,0,1,0
307487,456231,0,0,1,0,117000.000,1071909.0,31473.0,0.010147,-23125,...,0,0,0,0,0,0,0,0,0,0
307488,456232,0,0,0,0,157500.000,135000.0,13351.5,0.004960,-10092,...,0,0,0,0,0,0,0,0,1,0
307489,456233,0,0,1,0,225000.000,521280.0,23089.5,0.014464,-16471,...,0,0,0,0,0,0,1,0,0,1
307490,456234,0,0,1,0,81000.000,135000.0,9148.5,0.010147,-9874,...,0,0,0,0,0,0,0,0,0,0
307491,456235,0,1,1,2,90000.000,1078200.0,31522.5,0.019101,-10976,...,0,0,0,0,0,0,0,0,0,0
307492,456236,0,1,1,0,585000.000,1575000.0,43443.0,0.028663,-20965,...,0,0,0,0,0,0,0,0,0,0
307493,456237,0,0,1,0,135000.000,946764.0,37678.5,0.019689,-17533,...,0,0,0,0,0,0,0,0,0,0
307494,456238,0,1,0,1,270000.000,479700.0,46858.5,0.035792,-14958,...,0,0,0,0,0,0,0,0,0,0
307495,456239,0,1,0,0,180000.000,808650.0,23773.5,0.025164,-20922,...,0,0,0,0,0,1,0,0,1,0
307496,456240,1,0,0,0,360000.000,337500.0,16875.0,0.004960,-17345,...,0,0,0,0,0,0,0,0,0,0
307497,456241,0,1,1,0,180000.000,270126.0,12028.5,0.007020,-16679,...,0,0,0,0,0,0,0,0,0,0
307498,456242,0,1,1,0,198000.000,1312110.0,52168.5,0.072508,-19102,...,0,0,0,0,0,1,0,0,1,0
307499,456243,0,0,1,0,81000.000,225000.0,12694.5,0.007020,-16988,...,0,0,0,0,0,0,0,0,0,0
307500,456244,0,0,1,0,261000.000,1303812.0,35982.0,0.031329,-20390,...,0,0,0,0,0,1,0,0,1,0
307501,456245,0,0,1,3,81000.000,269550.0,11871.0,0.009175,-12961,...,0,0,0,0,0,0,1,0,1,0
307502,456246,0,0,1,1,94500.000,225000.0,10620.0,0.010966,-16063,...,0,0,0,0,0,0,0,0,0,0
307503,456247,0,0,1,0,112500.000,345510.0,17770.5,0.022800,-11870,...,0,0,0,0,0,0,0,0,0,0
307504,456248,0,0,1,0,153000.000,331920.0,16096.5,0.022625,-16705,...,0,0,0,0,0,0,0,0,0,0
307505,456249,0,0,1,0,112500.000,225000.0,22050.0,0.022800,-24384,...,0,0,0,0,0,1,0,0,1,0
307506,456251,0,0,0,0,157500.000,254700.0,27558.0,0.032561,-9327,...,0,0,0,0,0,0,1,0,1,0
307507,456252,0,0,1,0,72000.000,269550.0,12001.5,0.025164,-20775,...,0,0,0,0,0,0,1,0,1,0
307508,456253,0,0,1,0,153000.000,677664.0,29979.0,0.005002,-14966,...,0,0,0,0,0,1,0,0,1,0
307509,456254,0,0,1,0,171000.000,370107.0,20205.0,0.005313,-11961,...,0,0,0,0,0,0,1,0,1,0
307510,456255,0,0,0,0,157500.000,675000.0,49117.5,0.046220,-16856,...,0,0,0,0,0,1,0,0,1,0

In [57]:
print(app_train.isnull().sum())

SK_ID_CURR                                    0
NAME_CONTRACT_TYPE                            0
FLAG_OWN_CAR                                  0
FLAG_OWN_REALTY                               0
CNT_CHILDREN                                  0
AMT_INCOME_TOTAL                              0
AMT_CREDIT                                    0
AMT_ANNUITY                                  12
REGION_POPULATION_RELATIVE                    0
DAYS_BIRTH                                    0
DAYS_EMPLOYED                                 0
DAYS_REGISTRATION                             0
DAYS_ID_PUBLISH                               0
FLAG_WORK_PHONE                               0
FLAG_PHONE                                    0
FLAG_EMAIL                                    0
CNT_FAM_MEMBERS                               2
REGION_RATING_CLIENT                          0
REGION_RATING_CLIENT_W_CITY                   0
HOUR_APPR_PROCESS_START                       0
REG_REGION_NOT_WORK_REGION                    0
LIVE_REGION_NOT_WORK_REGION                   0
REG_CITY_NOT_LIVE_CITY                        0
REG_CITY_NOT_WORK_CITY                        0
LIVE_CITY_NOT_WORK_CITY                       0
EXT_SOURCE_1                             173378
EXT_SOURCE_2                                660
EXT_SOURCE_3                              60965
APARTMENTS_AVG                           156061
BASEMENTAREA_AVG                         179943
                                          ...
ORGANIZATION_TYPE_Security                    0
ORGANIZATION_TYPE_Security Ministries         0
ORGANIZATION_TYPE_Self-employed               0
ORGANIZATION_TYPE_Services                    0
ORGANIZATION_TYPE_Telecom                     0
ORGANIZATION_TYPE_Trade: type 1               0
ORGANIZATION_TYPE_Trade: type 2               0
ORGANIZATION_TYPE_Trade: type 3               0
ORGANIZATION_TYPE_Trade: type 4               0
ORGANIZATION_TYPE_Trade: type 5               0
ORGANIZATION_TYPE_Trade: type 6               0
ORGANIZATION_TYPE_Trade: type 7               0
ORGANIZATION_TYPE_Transport: type 1           0
ORGANIZATION_TYPE_Transport: type 2           0
ORGANIZATION_TYPE_Transport: type 3           0
ORGANIZATION_TYPE_Transport: type 4           0
ORGANIZATION_TYPE_University                  0
ORGANIZATION_TYPE_XNA                         0
HOUSETYPE_MODE_block of flats                 0
HOUSETYPE_MODE_specific housing               0
HOUSETYPE_MODE_terraced house                 0
WALLSMATERIAL_MODE_Block                      0
WALLSMATERIAL_MODE_Mixed                      0
WALLSMATERIAL_MODE_Monolithic                 0
WALLSMATERIAL_MODE_Others                     0
WALLSMATERIAL_MODE_Panel                      0
WALLSMATERIAL_MODE_Stone, brick               0
WALLSMATERIAL_MODE_Wooden                     0
EMERGENCYSTATE_MODE_No                        0
EMERGENCYSTATE_MODE_Yes                       0
Length: 196, dtype: int64

In [60]:
# Impute missing values

from sklearn.preprocessing import MinMaxScaler, Imputer

# Drop the target from the training data
if 'TARGET' in app_train:
    train = app_train.drop(columns = ['TARGET'])
else:
    train = app_train.copy()
    
# Feature names
features = list(train.columns)

# Copy of the testing data
#test = app_test.copy()

# Median imputation of missing values
imputer = Imputer(strategy = 'median')

# Scale each feature to 0-1
scaler = MinMaxScaler(feature_range = (0, 1))

# Fit on the training data
imputer.fit(train)

# Transform both training and testing data
train = imputer.transform(train)
#test = imputer.transform(app_test)

# Repeat with the scaler
scaler.fit(train)
train = scaler.transform(train)
#test = scaler.transform(test)

print('Training data shape: ', train.shape)
#print('Testing data shape: ', test.shape)

Training data shape:  (307511, 196)

In [63]:
train

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.80699391e-06, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [5.61398781e-06, 1.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [9.99994386e-01, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [9.99997193e-01, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

In [62]:
print(train.isnull().sum())

AttributeError: 'numpy.ndarray' object has no attribute 'isnull'